<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <NofVersion>11.0.0-nightly.1403070.ea4a5678</NofVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="AgentFn.Sdk" Version="0.3.0" />
    <PackageVersion Include="MailKit" Version="4.17.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.7" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="NOF.Application" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Contract" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Domain" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Hosting.AspNetCore" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Hosting.AspNetCore.Extension.OidcServer" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Infrastructure" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Infrastructure.EntityFrameworkCore" Version="$(NofVersion)" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
