// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quantum.Platform.Persistence;

#nullable disable

namespace Quantum.Platform.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    partial class PlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NOF.Infrastructure.NOFInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Route")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("CompletesOrderKey")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<string>("OrderKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id", "Route");

                    b.HasIndex("ClaimedBy");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.HasIndex("Status", "ClaimExpiresAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("Route", "OrderKey", "Sequence");

                    b.ToTable("NOFInboxMessage", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.NOFInboxOrderState", b =>
                {
                    b.Property<string>("Route")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OrderKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("BlockedSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("NextSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Route", "OrderKey");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.HasIndex("ClaimedBy", "ClaimExpiresAtUtc");

                    b.ToTable("NOFInboxOrderState", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.NOFOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("CompletesOrderKey")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DispatchRoutes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<string>("OrderKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("ClaimedBy");

                    b.HasIndex("TraceParent");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.HasIndex("OrderKey", "Sequence");

                    b.HasIndex("Status", "ClaimExpiresAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("NOFOutboxMessage", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.NOFOutboxOrderState", b =>
                {
                    b.Property<string>("OrderKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<bool>("CompletesOrderKey")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("OrderKey", "Sequence");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.ToTable("NOFOutboxOrderState", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.NOFTenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.HasIndex("Name", "__DeletedAtUnixTime")
                        .IsUnique();

                    b.ToTable("NOFTenant", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("Quantum.Platform.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ReleaseId")
                        .HasColumnType("bigint");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.HasIndex("ActorUserId", "OccurredAtUtc");

                    b.HasIndex("ListingId", "OccurredAtUtc");

                    b.ToTable("AuditEntry", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("Quantum.Platform.Domain.PlatformUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.HasIndex("Email", "__DeletedAtUnixTime")
                        .IsUnique();

                    b.HasIndex("Username", "__DeletedAtUnixTime")
                        .IsUnique();

                    b.ToTable("PlatformUser", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("Quantum.Platform.Domain.PluginListing", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.HasIndex("AuthorUserId", "UpdatedAtUtc");

                    b.HasIndex("PluginId", "__DeletedAtUnixTime")
                        .IsUnique();

                    b.ToTable("PluginListing", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("Quantum.Platform.Domain.PluginRelease", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("PackagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PackageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("PackageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("QuantumVersionSupport")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ReviewedByUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("__DeletedAtUnixTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("__DeletedAtUnixTime");

                    b.HasIndex("ListingId", "Version");

                    b.HasIndex("Status", "UploadedAtUtc");

                    b.HasIndex("ListingId", "Version", "__DeletedAtUnixTime")
                        .IsUnique();

                    b.ToTable("PluginRelease", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });
#pragma warning restore 612, 618
        }
    }
}
